#ifndef MYRTOS_PICO2W_H
#define MYRTOS_PICO2W_H

#include "rp2350.h"

#define PICO2W_DEFAULT_UART   UART0
#define PICO2W_UART_TX_PIN    0U
#define PICO2W_UART_RX_PIN    1U
#define PICO2W_UART_BAUDRATE  115200U

#define BOARD_DEFAULT_UART    PICO2W_DEFAULT_UART
#define BOARD_UART_BAUDRATE   PICO2W_UART_BAUDRATE

#define PERI_CLK_HZ           150000000UL

#define BOARD_SRAM_BASE       SRAM_BASE
#define BOARD_SRAM_SIZE       (520UL * 1024UL)
#define BOARD_FLASH_BASE      XIP_BASE
#define BOARD_FLASH_SIZE      PICO_FLASH_SIZE_BYTES
#define BOARD_IRQ_COUNT       52U
#define BOARD_MPU_ARMV8       1

#endif
