#!/usr/bin/env python3
"""Generate include/kernel/tcb_offsets.inc from tools/gen_tcb_offsets.c.

Cross-compiles with -S, parses the .word directives below each off_*
symbol, and writes a header that the PendSV/SVC/first_switch assembly can
`.include`. Using offsetof() against the real TCB means the assembly
offsets track kernel_types.h automatically.
"""
import argparse
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "tools" / "gen_tcb_offsets.c"
OUT = ROOT / "include" / "kernel" / "tcb_offsets.inc"
HEADER = """\
/* Auto-generated by scripts/gen_tcb_offsets.py. Do not edit. */
#ifndef TCB_OFFSETS_INC
#define TCB_OFFSETS_INC
"""
FOOTER = "#endif\n"

# Match "off_<name>:" then the next ".word N" or ".space 4" (zero value)
SYM_RE = re.compile(r"^off_([a-z0-9_]+):\s*$")
WORD_RE = re.compile(r"^\s*\.word\s+(0x[0-9a-fA-F]+|\d+)\s*$")
SPACE_RE = re.compile(r"^\s*\.space\s+4\s*$")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--cc", required=True)
    p.add_argument("--include", required=True)
    args = p.parse_args()

    import tempfile
    with tempfile.TemporaryDirectory() as td:
        asm_path = pathlib.Path(td) / "offsets.s"
        subprocess.run([args.cc, "-S", "-std=c11", "-O0",
                        "-I", args.include,
                        str(SRC), "-o", str(asm_path)],
                       check=True)
        asm = asm_path.read_text().splitlines()

    pairs = []
    pending = None
    for line in asm:
        m = SYM_RE.match(line)
        if m:
            pending = m.group(1).upper()
            continue
        if pending is None:
            continue
        w = WORD_RE.match(line)
        if w:
            pairs.append((pending, int(w.group(1), 0)))
            pending = None
            continue
        if SPACE_RE.match(line):
            # GCC emits ".space 4" for zero-valued 4-byte consts
            pairs.append((pending, 0))
            pending = None

    if not pairs:
        print("FAIL: no off_* symbols found in asm output", file=sys.stderr)
        sys.exit(1)

    body = "\n".join(f"#define OFF_{n} {v}" for n, v in pairs) + "\n"
    OUT.write_text(HEADER + body + FOOTER)
    print(f"OK: wrote {OUT} ({len(pairs)} offsets)")
    for n, v in pairs:
        print(f"  OFF_{n} = {v}")


if __name__ == "__main__":
    main()
